import type {
  IntelligenceServiceHandler,
  ServerContext,
  ListMarketImplicationsRequest,
  ListMarketImplicationsResponse,
  MarketImplicationCard,
} from '../../../../src/generated/server/worldmonitor/intelligence/v1/service_server';
import { readSeeded } from '../../../_shared/data-status';

const BASE_KEY = 'intelligence:market-implications:v1';
// Allowed framework IDs — prevents arbitrary Redis key injection
const ALLOWED_FRAMEWORK_IDS = new Set([
  'dalio-macro', 'buffett-value', 'pmesii-pt', 'doomsday-prepper',
]);

interface CachedTransmissionNode {
  node?: string;
  impact_type?: string;
  logic?: string;
}

interface CachedMarketImplication {
  ticker?: string;
  name?: string;
  direction?: string;
  timeframe?: string;
  confidence?: string;
  title?: string;
  narrative?: string;
  risk_caveat?: string;
  driver?: string;
  transmission_chain?: CachedTransmissionNode[];
}

interface CachedMarketImplicationsData {
  cards?: CachedMarketImplication[];
  generatedAt?: string;
}

function toCard(raw: CachedMarketImplication): MarketImplicationCard {
  return {
    ticker: raw.ticker ?? '',
    name: raw.name ?? '',
    direction: raw.direction ?? '',
    timeframe: raw.timeframe ?? '',
    confidence: raw.confidence ?? '',
    title: raw.title ?? '',
    narrative: raw.narrative ?? '',
    riskCaveat: raw.risk_caveat ?? '',
    driver: raw.driver ?? '',
    transmissionChain: Array.isArray(raw.transmission_chain)
      ? raw.transmission_chain.map(n => ({
          node: n.node ?? '',
          impactType: n.impact_type ?? '',
          logic: n.logic ?? '',
        }))
      : [],
  };
}

export const listMarketImplications: IntelligenceServiceHandler['listMarketImplications'] = async (
  _ctx: ServerContext,
  req: ListMarketImplicationsRequest,
): Promise<ListMarketImplicationsResponse> => {
  const fwId = req.frameworkId && ALLOWED_FRAMEWORK_IDS.has(req.frameworkId) ? req.frameworkId : null;
  const redisKey = fwId ? `${BASE_KEY}:${fwId}` : BASE_KEY;
  // If framework-specific key misses, fall back to default (generated by cron)
  // A cascade: the framework-specific key falls back to the cron-generated base
  // key. Both `.catch(() => null)` calls folded a Redis fault into the same null
  // a never-written key produces, which is what `emptyReason` then reported as
  // 'data_unavailable' regardless of which had happened.
  const primary = await readSeeded<CachedMarketImplicationsData>(
    redisKey, 'the market-implications cron has not written this framework');
  let data = primary.data;
  let status = primary.status;
  let usedFallback = false;
  if (!data && fwId) {
    const base = await readSeeded<CachedMarketImplicationsData>(
      BASE_KEY, 'the market-implications cron has not written the default set');
    if (base.data) { data = base.data; status = base.status; usedFallback = true; }
  }

  if (!data || !Array.isArray(data.cards) || data.cards.length === 0) {
    return {
      cards: [],
      degraded: true,
      emptyReason: data ? 'no_cards' : 'data_unavailable',
      generatedAt: '',
      dataStatus: data
        ? { fetchedAt: status.fetchedAt, availability: 'DATA_AVAILABILITY_EMPTY', detail: 'the framework was read successfully and contains no cards' }
        : status,
    };
  }

  return {
    cards: data.cards.map(toCard),
    degraded: false,
    emptyReason: '',
    generatedAt: data.generatedAt ?? '',
    dataStatus: usedFallback
      ? { fetchedAt: status.fetchedAt, availability: 'DATA_AVAILABILITY_STALE',
          detail: `no cards for framework "${fwId}"; serving the default set` }
      : status,
  };
};
